version: "3"
services:
  db:
    image: postgres:17-bookworm
    container_name: postgres17_store
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: store
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_store
    restart: always
    ports:
      - "8888:80"

    networks:
      - default
    environment:
      PGADMIN_DEFAULT_EMAIL: iphonemarlon@gmail.com
      PGADMIN_DEFAULT_PASSWORD: p
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres: ~
  pgadmin-data: ~

